= Frequently Asked Questions

== Difference with the On-premise version

Bonita Cloud *IS NOT* a downgraded On-premise version.
On-premises or in the Cloud. Same:

* Technology
* Features
* Customizations
* Connectors

== Platform setup

=== Runtime URLs

==== What are the default runtime URLs?

Production

* *_customer-name_*.bonitacloud.com

Pre-production

* *_customer-name_*-preproduction.bonitacloud.com

Integration

* *_customer-name_*-integration.bonitacloud.com

==== Can I customize the URLs?

Yes, the URLs of the runtime can be customized upon request.

=== Can I configure Single sign-on (SSO)?

Yes, Bonita Cloud supports several SSO protocols.

=== Can I configure a VPN?

Yes, Bonita Clouds supports VPN.

=== Bonita licenses have a short-term expiration date. Do I need to worry about it?

Bonita licenses on Bonita Cloud runtimes are automatically renewed 10 days before their expiration date, as long as your subscription is active. You do not need to worry about it.

NOTE: Licenses generated for Bonita Cloud runtimes are valid for 40 days. Therefore you might be surprised to see in the Portal that your license will expire soon. As described above, a new 40-day license will be automatically installed.


=== Service region

==== What are possible regions for Bonita Cloud?

Bonita Cloud is currently available in Europe and North America:

|===
| North America | Europe

| Canada        | Ireland
| United States | United Kingdom
|               | France
|               | Germany

|===

// #### Can I move my platform from one region to another?
// List again + it is possible to move

=== Which database vendor does Bonita Cloud runtimes use?

Bonita Cloud runtimes use PostgreSQL.

=== I already have a continuous delivery platform. Can I use it with Bonita Cloud?

Yes. Thanks to our https://documentation.bonitasoft.com/bcd/latest/[Bonita Cloud Continuous Delivery add-on] you can use your pre-existing tools to manage your applications deployment on Bonita Cloud.


//== Monitoring
//
//=== Who is monitoring Bonita Cloud ?
//
//== Security
//
//=== How is Bonitasoft managing security for Bonita Cloud? -->
