= Frequently Asked Questions

:description: This page provides short answers to frequently asked questions about Bonita Cloud.

== Difference with the On-premise version

Bonita Cloud *IS NOT* a downgraded On-premise version.
On-premises or in the Cloud. Same:

* Technology
* Features
* Customizations
* Connectors

== Platform setup

=== Runtime URLs

==== What are the default runtime URLs?

Production

* *_customer-name_*.bonitacloud.com

Pre-production

* *_customer-name_*-preproduction.bonitacloud.com

Integration

* *_customer-name_*-integration.bonitacloud.com

==== Can I customize the URLs?

Yes, the URLs of the runtime can be customized upon request.

=== Can I configure Single sign-on (SSO)?

Yes, Bonita Cloud supports several SSO protocols.

=== Can I configure a VPN?

Currently, Bonita Cloud's architecture is designed without support for client VPN configurations.

=== Bonita licenses have a short-term expiration date. Do I need to worry about it?

Bonita licenses on Bonita Cloud runtimes are automatically renewed 10 days before their expiration date, as long as your subscription is active. You do not need to worry about it.

NOTE: Licenses generated for Bonita Cloud runtimes are valid for 40 days. Therefore, you might be surprised to see in the Portal that your license will expire soon. As described above, a new 40-day license will be automatically installed.

=== How is Bonita Cloud operated?

Our architecture is based on Docker containers and Kubernetes as an orchestrator.

The primary objective is to be able to ensure an optimal quality of service: uptime guarantee, performance guarantee, cost optimization.


=== Service region

==== What are possible regions for Bonita Cloud?

Bonita Cloud is currently available in Europe and North America:

|===
| North America | Europe

| Canada        | Ireland
| United States | United Kingdom
|               | France
|               | Germany

|===

// #### Can I move my platform from one region to another?
// List again + it is possible to move

=== Which database vendor does Bonita Cloud runtimes use?

Bonita Cloud runtimes use PostgreSQL.

=== I already have a continuous delivery platform. Can I use it with Bonita Cloud?

Yes. Thanks to our xref:{bcdVersion}@bcd:ROOT:index.adoc[Bonita Cloud Continuous Delivery add-on] you can use your pre-existing tools to manage your applications deployment on Bonita Cloud.


== Infrastructure access

Bonita Cloud infrastructure follows the security standard to guarantee data confidentiality and reliability.
The Bonitasoft cloud infrastructure team guarantees the best level of service on the infrastructure by ensuring strict security processes compliance.

In consequence, Bonitasoft doesn't give direct access to infrastructure components used by the Bonita Cloud services (i.e. machine, database, file system, ...).
Moreover, this protection ensures any mis-usage or bad manipulation by the users that would put at risk the Bonita Cloud SLA.

Nevertheless, there are multiple options to retrieve and integrate Bonita data to an external system, for instance:

- Using Bonita API to access data
- Implement a connector
- Or ask our Professional Services team to implement an Event Handler.

Just contact your Bonita Cloud representative for more information.

//== Monitoring
//
//=== Who is monitoring Bonita Cloud ?
//
//== Security
//
//=== How is Bonitasoft managing security for Bonita Cloud? -->
