= Single Sign-On Configuration

:description: This page explains how to configure Single Sign-On.

To simplify the access to your Bonita applications and processes, you can request the setup of a Single-Sign-On authentication for Bonita Cloud.

Bonita Cloud currently supports SAML and OIDC protocols.

NOTE: You will need a SAML or OIDC Identity Provider server up and running


== Requesting Single-Sign-On authentication

To request SSO authentication to Bonita Cloud, create a new case on the Customer Service Center. Select _Professional Services_ as the type of request and make sure to provide the following information in your case:

* The AppRuntimes that will use the SSO

For SAML

* SAML metadata XML
* Encryption and signatures needs

For OIDC

* The following bonita configuration files (see xref:{bonitaDocVersion}@bonita:identity:single-sign-on-with-oidc.adoc[OpenID Connect SSO configuration] documentation):
** authenticationManager-config.properties
** bonita-tenant-sp-custom.properties
** keycloak-oidc.json
