= URL customization

You can request to customize your domain to have an URL that uses a domain different from the default one (* bonitacloud.com).

[NOTE]
====
* You will need to own the targeted domain or subdomain and delegate its management to Bonita.
* This customization is a paid option.
====

== Requesting a URL customization

First, contact your sales or customer success representative to subscribe to this option.

Then create a new support case to request a URL Customization of your Bonita Cloud. Make sure to provide the following information in your case:

* The domain or sub-domain to delegate to Bonita

NOTE: The same domain must be applied to all environments.


* The current and new environment **F**ully **Q**ualified **D**omain **N**ame:

|===
| Environment | Current FQDN | New FQDN

| Integration
| _Example: customer-name-integration.bonitacloud.com_
| _Example: integration.mydomain.com_

| Pre-production
| _Example: customer-name-preproduction.bonitacloud.com_
| _Example: preproduction.mydomain.com_

| Production
| _Example: customer-name.bonitacloud.com_
| _Example: projectname.mydomain.com_

| ...
|
|
|===

Bonita will provide the corresponding DNS configuration (Name Servers) to delegate your domain or subdomain.

NOTE: To limit the time to take DNS changes into account, ensure to minimize the TTL of NS entries (300 seconds for example) before delegating your domain to Bonita Name Servers.


Bonita manages the certificate lifecycle (request, validation, and renewal).
