= URL customization

You can request to customize your domain to have an URL that uses a domain different from the default one (*.bonitacloud.com).

[NOTE]
====
* You must own the targeted domain or subdomain and delegate its management to Bonita.
** Bonita manages the SSL certificate lifecycle (request, validation, and renewal).
* This customization is a paid option.
====

== Requesting an URL customization

=== Step 1: Subscribe to the option

Contact your sales or customer success representative to subscribe to this option.

=== Step 2: Open a support case

Create a new support case to request a URL Customization of your Bonita Cloud environments. Make sure to provide the following information in your case:

* The domain (example: **mydomain.com**) or subdomain (example: **subdomain.mydomain.com**) to delegate to Bonita.

NOTE: This request requires you to delegate responsability of the **whole domain name (or subdomain)** to the Bonita Cloud DNS service. Besides, the same domain (or subdomain) will be applied to all environments.

* The current and new environment Fully Qualified Domain Name (FQDN) as follows:
|===
| Environment | Current FQDN | New FQDN

| Integration
| _Example: customer-name-integration.bonitacloud.com_
| _Example: integration.mydomain.com OR integration.subdomain.mydomain.com_

| Pre-production
| _Example: customer-name-preproduction.bonitacloud.com_
| _Example: preproduction.mydomain.com OR preproduction.subdomain.mydomain.com_

| Production
| _Example: customer-name.bonitacloud.com_
| _Example: projectname.mydomain.com OR projectname.subdomain.mydomain.com_

| Continuous delivery
| _Example: customer-name-cd.bonitacloud.com_
| _Example: cd.mydomain.com OR cd.subdomain.mydomain.com_

| ...
|
|
|===

=== Step 3: Perform the delegation with low TTL

Bonita will provide the corresponding DNS configuration (Name Servers) to delegate your domain or subdomain.

NOTE: To limit the time to take DNS changes into account, ensure to minimize the TTL (time to live) of NS entries (300 seconds for example) before delegating your domain to Bonita Name Servers. NS stands for 'name server', it's the type of the record that indicates which DNS servers are authoritative for that domain.

=== Step 4: Schedule the change

Bonitasoft will confirm with you a window maintenance to perform this customization. You will have to inform accordingly your end users about that change.

=== Step 5: Change NS TTL back to a higher value

Once the new URLs are in place, you will be able to change the TTL for the NS record back to a higher value, for example, 172800 seconds (two days). This will improves latency for your users.
