= Test a living application on Non Production AppRuntimes
:description: Learn how to test a living application on Non Production AppRuntimes
:page-aliases: ROOT:Continuous_Delivery_Test_a_Living_Application.adoc


[NOTE]
====
This functionality is compatible with Bonita Cloud AppRuntimes >= 2022.1 / 7.14.

It only targets non-production AppRuntimes.
====

In order to write and execute integration tests for your Bonita processes the Bonita Cloud Continuous Delivery platform integrates the xref:test-toolkit:ROOT:process-testing-overview.adoc[Bonita Test Toolkit].

It requires to include a subfolder in your Bonita project within the same git repository.

Then create your integration tests following the xref:test-toolkit:ROOT:quick-start.adoc#quick-start-test[Test Toolkit documentation].

You will be able to launch your integrations tests by specifying into xref:living-application/deploying-to-bonita-cloud.adoc[deploy] or xref:living-application/build-and-deploy.adoc[build and deploy] jobs the folder where you have stored your tests through the INTEGRATION_TESTS_DIR parameter.
